server:
  port: 8088
---
spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: app
          uri: http://localhost:8081
          predicates:
            - Path=/reservations/**, /retrieveReservations/**, /retrieveMovies/**
        - id: pay
          uri: http://localhost:8082
          predicates:
            - Path=/approvals/**
        - id: movie
          uri: http://localhost:8083
          predicates:
            - Path=/movieManagements/**, /movieInquiries/**, /listinqueries/**, /detailinqueries/**
        - id: theater
          uri: http://localhost:8084
          predicates:
            - Path=/movieSeats/**, /movies/**, /reservationavailabilityinquiries/**
        - id: notice
          uri: http://localhost:8085
          predicates:
            - Path=
        - id: customercenter
          uri: http://localhost:8086
          predicates:
            - Path=/bookInfos/**, /mypages/**
        - id: ticketing
          uri: http://localhost:8087
          predicates:
            - Path=/tickets/**, /printTickets/**
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
---
spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: app
          uri: http://app:8080
          predicates:
            - Path=/reservations/**, /retrieveReservations/**, /retrieveMovies/**
        - id: pay
          uri: http://pay:8080
          predicates:
            - Path=/approvals/**
        - id: movie
          uri: http://movie:8080
          predicates:
            - Path=/movieManagements/**, /movieInquiries/**, /listinqueries/**, /detailinqueries/**
        - id: theater
          uri: http://theater:8080
          predicates:
            - Path=/movieSeats/**, /movies/**, /reservationavailabilityinquiries/**
        - id: notice
          uri: http://notice:8080
          predicates:
            - Path=
        - id: customercenter
          uri: http://customercenter:8080
          predicates:
            - Path=/bookInfos/**, /mypages/**
        - id: ticketing
          uri: http://ticketing:8080
          predicates:
            - Path=/tickets/**, /printTickets/**
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
